name: CD - Deploy with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download image tag
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Read image tag
        id: image
        run: |
          tag=$(cat tag.txt)
          echo "tag=$tag" >> $GITHUB_OUTPUT

     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var="image_tag=${{ steps.image.outputs.tag }}"
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ steps.image.outputs.tag }}"
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
